Update OpenTitan EDN registers and `SW_CMD_STS` behavior
lowRISC/qemu pull request #85
Opened 2024-12-05 12:22 UTC by luismarques

2024-12-05 13:56 UTC, AlexJones0 approved these changes
Thanks @luismarques, these changes all appear to match the latest EDN docs to me.

2024-12-05 13:56 UTC, AlexJones0 commented on hw/opentitan/ot_edn.c
> +    uint8_t last_cmd_status; /* status of the last CSRNG command */
Is there a reason that this has type `uint8_t` and not `OtCSRNGCmdStatus`?

2024-12-05 14:06 UTC, luismarques commented on hw/opentitan/ot_edn.c
> +    uint8_t last_cmd_status; /* status of the last CSRNG command */
My preferred way to do that would be to declare the enum using `enum OtCSRNGCmdStatus : uint8_t`, and then the `last_cmd_status` as a `OtCSRNGCmdStatus`. But that requires C23. I don't mind changing `last_cmd_status` to `OtCSRNGCmdStatus`, though it takes a few extra bytes, and the actual status field is only 3 bits or something like that.

2024-12-05 14:15 UTC, AlexJones0 commented on hw/opentitan/ot_edn.c
> +    uint8_t last_cmd_status; /* status of the last CSRNG command */
That makes sense, thanks for the explanation. I think this is fine to stay as is - the status field should not really ever have more than 256 values.

2024-12-05 16:11 UTC, rivos-eblot requested changes

2024-12-05 16:11 UTC, rivos-eblot commented on hw/opentitan/ot_edn.c
> +        uint32_t rdy = ot_edn_is_cmd_rdy(s, false);
Some explicit cast (bool -> uint32_t) would be better.

2024-12-05 16:11 UTC, rivos-eblot commented on hw/opentitan/ot_edn.c
> +    uint8_t last_cmd_status; /* status of the last CSRNG command */
We add the very same requirement this very week :-)
Following a review on our side that I have yet to push, could you add a comment about the use of this 8-bit value? BTW C99 enum are (signed) integers, so I think `int8_t` would be better.

2024-12-05 16:11 UTC, rivos-eblot commented on hw/opentitan/ot_edn.c
> +    uint8_t last_cmd_status; /* status of the last CSRNG command */
and maybe moved it towards line 199 along with other enums as it would introduce the field in the structure.

2024-12-05 18:16 UTC, rivos-eblot commented on hw/opentitan/ot_edn.c
> +    uint8_t last_cmd_status; /* status of the last CSRNG command */
> We had the very same requirement this very week :-) 
https://github.com/lowRISC/qemu/pull/87/commits/a4ebcfa7fd7493b343541b7d51621dbfa6e3a21d#diff-6ee28781a2f1e2a1bdcb93dd29e5811f27b14d2466bfcfc95433f71fe3aee527R381

2024-12-06 11:47 UTC, luismarques commented on hw/opentitan/ot_edn.c
> +    uint8_t last_cmd_status; /* status of the last CSRNG command */
> We had the very same requirement this very week :-) Following a review on our side that I have yet to push, could you add a comment about the use of this 8-bit value? BTW C99 enum are (signed) integers, so I think `int8_t` would be better.

OK, I just typed the member variable with the enum type. That avoids the need for the comment, sidesteps the `uint8_t` vs `int8_t` issue, and when QEMU later adopts C23 we can just type the enum as `uint8_t`.

2024-12-09 08:09 UTC, rivos-eblot approved these changes
LGTM.

2024-12-09 13:04 UTC, merged