Update PLIC IDs for new interrupts
lowRISC/qemu pull request #86
Opened 2024-12-05 14:26 UTC by jwnrt

WIP, still need to update the GPIOs in the actual blocks to reflect changes in interrupts.

2024-12-05 16:14 UTC, rivos-eblot requested changes

2024-12-05 16:14 UTC, rivos-eblot commented on hw/opentitan/ot_hmac.c
> +    r->cfg = 0x4100;
Please favor an unsigned constant (`u` suffix)

2024-12-05 16:14 UTC, rivos-eblot commented on hw/opentitan/ot_hmac.c
> +    r->cfg = 0x4100;
(or even better use the REG32 macro if you want to, this is something we failed to do up to now :-()

2024-12-10 14:49 UTC, rivos-eblot requested changes

2024-12-10 14:49 UTC, rivos-eblot commented on .github/workflows/build_test.yaml
> +      # - name: Check Darjeeling VM execution
Please remove these lines for now (avoid dead "code"). Thanks

2024-12-10 14:49 UTC, rivos-eblot commented on hw/opentitan/ot_spi_device.c
> +SHARED_FIELD(INTR_UPLOAD_CMDFIFO_NOT_EMPTY, 0u, 1u)
I just noticed that the original version has been trashed, likely by `clang-format`.

Can you indent (4 space char) the `FIELD` and `SHARED_FIELD` lines, and add the missing `/* clang-format off */` comment before the first register definition and `/* clang-format on */` after the last one? Thanks.

2024-12-10 14:49 UTC, rivos-eblot commented on hw/opentitan/ot_spi_device.c
> +        case CTRL_MODE_DISABLED:
I would expected a `LOG_GUEST_ERROR` here (?)

2024-12-10 14:49 UTC, rivos-eblot commented on hw/opentitan/ot_spi_device.c
> -    /* if phase or polarity does not match, corrupt data */
I think the incoming packet mode still need to be checked, as if the remote end sends invalid SPI mode (phase/polarity) there is no chance for the communication to succeed.

2024-12-10 14:49 UTC, rivos-eblot commented on hw/opentitan/ot_uart.c
> +    SHARED_FIELD(INTR_TX_DONE, 2u, 1u)
I think you need to add a minimal support for this, as a user would end up having code that does not work and no clue about the failure. This is especially senstive since for some reason the RTL designers have elected to break the compatibilty by relocating an existing bit :-(

If this interrupt is enabled (`INTR_ENABLE`), a `LOG_UNIMP` should be emitted till it is actually supported in an upcoming MR.

2024-12-11 13:52 UTC, rivos-eblot commented
Coud you add the component the change applies to in the commit message, such as `[ot] hw/opentitan: ot_uart: <msg>`. Thanks

2024-12-13 13:32 UTC, jwnrt commented on hw/opentitan/ot_spi_device.c
> +        case CTRL_MODE_DISABLED:
I'm going to `LOG_UNIMP` until disabling is properly implemented.

2024-12-13 13:51 UTC, jwnrt commented on hw/opentitan/ot_uart.c
> +    SHARED_FIELD(INTR_TX_DONE, 2u, 1u)
Sure, it's the same as `TX_EMPTY` within QEMU anyway, I was just being lazy.

2024-12-13 13:52 UTC, jwnrt commented on hw/opentitan/ot_spi_device.c
> -    /* if phase or polarity does not match, corrupt data */
Our SPI_DEVICE now only supports mode 0. Let me know if I've done the check correctly.

2024-12-13 14:15 UTC, rivos-eblot commented on hw/opentitan/ot_spi_device.c
> -    /* if phase or polarity does not match, corrupt data */
I think so, but I'm really bad at this exercise (as figuring it out the byte order in crypto things) :)

2024-12-13 14:20 UTC, rivos-eblot approved these changes
LGTM

2024-12-13 14:27 UTC, jwnrt commented on hw/opentitan/ot_spi_device.c
> -    /* if phase or polarity does not match, corrupt data */
Oh definitely. We spent a long time going in circles in the office over the HMAC byte ordering code in the other PR.

Thanks for checking

2024-12-13 14:27 UTC, merged