Add HMAC stop/continue commands & endian swaps
lowRISC/qemu pull request #88
Opened 2024-12-10 14:40 UTC by AlexJones0

This PR partially updates Earlgrey's HMAC to match the latest hardware interface changes. It adds digest write-back during SHA256 processing to allow for saving and restoring of partial hash context, adds support for the `Stop`/`Continue` commands used to do this, and updates the supporting message length and digest registers. It also implements the new key/digest swap config fields, and makes a couple other small fixes. See the commit messages for more details.
**Note:** the first commit 1d539a558f310048f54bd4e32971e84e1de57e61 is taken from #86, as that applies to the HMAC and is required for functional operation.

Tested against existing passing tests `hmac_enc_idle_test` and `hmac_smoketest` and previously failing test `wots_test` from [`master`](https://github.com/lowrisc/opentitan/commits/b70973d2e9a3705361425d59a5e64a660b6fe1fc) on OpenTitan.

2024-12-10 15:00 UTC, rivos-eblot reviewed
couple of minor syntax tweaks

2024-12-10 15:00 UTC, rivos-eblot commented on hw/opentitan/ot_hmac.c
> +            // Restore SHA256 context
Need to be a C-style comment (QEMU rule)

2024-12-10 15:00 UTC, rivos-eblot commented on hw/opentitan/ot_hmac.c
> +    const bool stop = s->regs->cmd & R_CMD_HASH_STOP_MASK;
you can remove the `const` here

2024-12-10 15:00 UTC, rivos-eblot commented on hw/opentitan/ot_hmac.c
> +            for (uint8_t i = 0; i < 8; i++) {
please favor unsigned for loop when possible & at least two chars for the loop variable, and 8u for the constant

2024-12-10 15:00 UTC, rivos-eblot commented on hw/opentitan/ot_hmac.c
> +    for (uint8_t i = 0; i < 8; i++) {
please favor unsigned for loop when possible & at least two chars for the loop variable, and 8u for the constant

2024-12-10 15:00 UTC, rivos-eblot commented on hw/opentitan/ot_hmac.c
> +            ot_hmac_sha_process(s, &value, 1, false);
1u

2024-12-10 15:00 UTC, rivos-eblot commented on hw/opentitan/ot_hmac.c
> +    if (process && s->ctx->state.sha256.length >= 512) {
512u
(`ulong64`)

2024-12-10 15:02 UTC, rivos-eblot commented
(adding Loïc as a reviewer, since he better knows the HMAC implementation than I do)

2024-12-10 15:16 UTC, AlexJones0 commented on hw/opentitan/ot_hmac.c
> +            for (uint8_t i = 0; i < 8; i++) {
Thanks - I've opted to replace the `8` with the calculation used for the size of the digest register array, so that the logic stays correct even if e.g. the digest length were to change in some top in the future.

2024-12-10 15:24 UTC, rivos-eblot commented on hw/opentitan/ot_hmac.c
> +    /* copy intermediary digest to mock HMAC operation for stop/continue behaviour. */
I think this line overflows the 80-col limit (I'm not sure clang-format checks the comment lines)

2024-12-10 15:41 UTC, AlexJones0 commented on hw/opentitan/ot_hmac.c
> +    /* copy intermediary digest to mock HMAC operation for stop/continue behaviour. */
Ah, you're right, good spot - I assumed `clang-format` would check this. Can we configure this so that `clang-format` will handle this by default?

2024-12-10 15:49 UTC, rivos-eblot commented on hw/opentitan/ot_hmac.c
> +    /* copy intermediary digest to mock HMAC operation for stop/continue behaviour. */
I'm not sure we can, and we may hit some corner cases such as storing a URL which cannot be split for example :(

2024-12-10 15:52 UTC, AlexJones0 commented on hw/opentitan/ot_hmac.c
> +    /* copy intermediary digest to mock HMAC operation for stop/continue behaviour. */
That makes sense. I think `clang-tidy` can do this, but I seem to run into some issues when using `ot-tidy.sh` (errors/warnings unrelated to areas I've changed).

2024-12-11 13:50 UTC, rivos-eblot requested changes
Very sorry. I missed this point last time:

Can you add the component the change applies to in the commit message:
`[ot] hw/opentitan: ot_hmac: <msg>`

I think it would be nice to add this kind of checks in the CI BTW (I never took the time to implement this...)

Otherwise, LGTM.

2024-12-11 14:31 UTC, AlexJones0 commented
Force push adds the component to the commit messages, and corrects one small error (message length does not have to be >= 512 to process, that was a misunderstanding on my part). 

I've also now tested it on top of #86 and can see that this seems to be fixing several tests that were failing (`wots_test`, `verify_test_hardcoded`, `hmac_sha256_functest` and `fors_test`).

2024-12-11 14:31 UTC, rivos-eblot approved these changes
LGTM

2024-12-11 15:09 UTC, merged